# Generated by Django 5.0.1 on 2024-01-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('being_cooked', 'Being Cooked'), ('being_prepared', 'Being Prepared'), ('being_delivered', 'Being Delivered'), ('completed', 'Completed')], default='new', max_length=20)),
                ('new_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('start_cooking_at', models.DateTimeField(blank=True, null=True)),
                ('start_preparing_at', models.DateTimeField(blank=True, null=True)),
                ('start_delivering_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
